name: Android CI - Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build APK (download Gradle and run)
        run: |
          set -eux
          GRADLE_VERSION=8.4.1
          GRADLE_ZIP=gradle-${GRADLE_VERSION}-bin.zip
          curl -fsSL "https://services.gradle.org/distributions/${GRADLE_ZIP}" -o "/tmp/${GRADLE_ZIP}"
          sudo mkdir -p /opt/gradle
          sudo unzip -q -o "/tmp/${GRADLE_ZIP}" -d /opt/gradle
          export PATH="/opt/gradle/gradle-${GRADLE_VERSION}/bin:$PATH"
          gradle --version
          cd android
          gradle assembleDebug --no-daemon --console=plain
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/*.apk
