name: Android CI - Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Android SDK command-line tools and platforms
        run: |
          set -eux
          SDK_ROOT="$HOME/android-sdk"
          mkdir -p "$SDK_ROOT"
          export ANDROID_SDK_ROOT="$SDK_ROOT"
          # Download commandline tools (stable known URL may change; this one is commonly available)
          CLI_ZIP="commandlinetools-linux_latest.zip"
          curl -fsSL "https://dl.google.com/android/repository/commandlinetools-linux_latest.zip" -o /tmp/$CLI_ZIP
          mkdir -p "$SDK_ROOT/cmdline-tools/latest"
          unzip -q /tmp/$CLI_ZIP -d "$SDK_ROOT/cmdline-tools/latest"
          export PATH="$SDK_ROOT/cmdline-tools/latest/cmdline-tools/bin:$PATH"
          yes | sdkmanager --licenses || true
          sdkmanager --sdk_root="$SDK_ROOT" "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"
          ls -la "$SDK_ROOT"

      - name: Install Gradle and build (generate wrapper if missing)
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y gradle unzip
          gradle --version
          cd android
          # If no gradlew exists, generate a wrapper using installed gradle
          if [ ! -f ./gradlew ]; then
            gradle wrapper
          fi
          ./gradlew assembleDebug --no-daemon --console=plain
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/*.apk
